<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>
    
    <!-- LIFTING ACTUATOR LEFT -->
    <xacro:property name="actuator_fixed_length" value="0.5" />
    <xacro:property name="actuator_extension_length" value="0.2" />
    <xacro:property name="actuator_radius" value="0.02" />
    
    
    <!-- FIXED PART -->
    <joint name="actuator_left_joint" type="fixed">
        <parent link="left_arm_link"/>
        <child link="actuator_left"/>
        <origin xyz="0.2325 0.125 0.25" rpy="0 ${pi/6} 0"/>
        <axis xyz="1 0 0"/>
    </joint>

    <link name="actuator_left">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${actuator_fixed_length} ${actuator_radius} ${actuator_radius}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${actuator_fixed_length} ${actuator_radius} ${actuator_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="1.5" x="${actuator_fixed_length}" y="${actuator_radius}" z="${actuator_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="actuator_left">
        <material>Gazebo/Blue</material>
    </gazebo>
    
    <!-- MOVING PART -->
    <joint name="lifting_left_joint" type="prismatic">
        <parent link="actuator_left"/>
        <child link="lifting_left_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <axis xyz="1 0 0"/>
        <limit lower="0.15" upper="0.35" velocity="100" effort="100"/>
    </joint>

    <link name="lifting_left_link">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${actuator_extension_length} ${actuator_radius} ${actuator_radius}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${actuator_extension_length} ${actuator_radius} ${actuator_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.2" x="${actuator_extension_length}" y="${actuator_radius}" z="${actuator_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="lifting_left_link">
        <material>Gazebo/Orange</material>
    </gazebo>

    
    <!-- LIFTING ACTUATOR RIGHT -->
    
    <!-- FIXED PART -->
    <joint name="actuator_right_joint" type="fixed">
        <parent link="left_arm_link"/>
        <child link="actuator_right"/>
        <origin xyz="0.2325 -0.125 0.25" rpy="0 ${pi/6} 0"/>
        <axis xyz="1 0 0"/>
    </joint>

    <link name="actuator_right">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${actuator_fixed_length} ${actuator_radius} ${actuator_radius}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${actuator_fixed_length} ${actuator_radius} ${actuator_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.2" x="${actuator_fixed_length}" y="${actuator_radius}" z="${actuator_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="actuator_right">
        <material>Gazebo/Blue</material>
    </gazebo>
    

    
    <!-- CONNECTOR -->
    <joint name="connecting_joint" type="fixed">
        <parent link="lifting_left_link"/>
        <child link="connecting_link"/>
        <origin xyz="-0.2 -0.125 0"/>
    </joint>

    <link name="connecting_link">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="0.02 0.23 0.02"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="0.02 0.23 0.02"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.2" x="0.02" y="0.23" z="0.02">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="connecting_link">
        <material>Gazebo/Orange</material>
    </gazebo>



    <!-- MOVING PART -->
    <joint name="lifting_right_joint" type="fixed">
        <parent link="connecting_link"/>
        <child link="lifting_right_link"/>
        <origin xyz="0.2 -0.125 0" rpy="0 0 0"/>
        <axis xyz="1 0 0"/>
    </joint>

    <link name="lifting_right_link">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${actuator_extension_length} 0.02 0.02"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${actuator_extension_length} 0.02 0.02"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.2" x="${actuator_extension_length}" y="0.02" z="0.02">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="lifting_right_link">
        <material>Gazebo/Orange</material>
    </gazebo>
    
    
    
    
   
    
    
    
    <!-- LEFT ARM JOINT -->
    <!-- arm_joint describes the rotation of the arm and is centred around the top corner of the slider box. -->
    <!-- - The axis of rotation is -1 in Y, so that positive is "up" -->
    <!-- - The upper limit uses xacro's mathematical features -->
    <joint name="left_arm_joint" type="revolute">
        <origin xyz="0.025 0 0.05" rpy="0 0 0"/>
        <parent link="tower"/>
        <child link="left_arm_link"/>
        <axis xyz="0 -1 0"/>
        <limit lower="0" upper="${pi/4}" velocity="50" effort="100"/> 
    </joint>


    <!-- arm_link describes the arm -->
    <!-- - We use the "property" feature to define the arm length and radius and use them multiple times -->
    <!-- - The visual/collision origin is set to halfway along the length (similar to the box), but also with a rotation (again using the mathematical features). -->
    <!--   This is because the cylinder extends along the Z axis by default, but we want it to be along the X axis (when the joint is at 0) -->

    <xacro:property name="arm_length" value="0.75" />
    <xacro:property name="arm_radius" value="0.02" />
    <link name="left_arm_link">
        <visual>
            <origin xyz="${arm_length/2} -0.125 0"/>
            <geometry>                
                <box size="${arm_length} ${arm_radius} ${arm_radius}" />
            </geometry>
            <material name="orange" />
        </visual>
        <collision>
            <origin xyz="${arm_length/2} -0.125 0"/>
            <geometry>
                <box size="${arm_length} ${arm_radius} ${arm_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.075" x="${arm_length}" y="${arm_radius}" z="${arm_radius}">
            <origin xyz="${arm_length/2} -0.125 0"/>
        </xacro:inertial_box>
    </link>
    
    <gazebo reference="left_arm_link">
        <material>Gazebo/Blue</material>
    </gazebo>
    
    


    <!-- ARM CONNECTING LINK -->

    <joint name="arm_joint" type="fixed">
        <parent link="left_arm_link"/>
        <child link="arm_link"/>
        <origin xyz="0.15 0 0"/>
    </joint>

    <link name="arm_link">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${arm_radius} 0.23 ${arm_radius}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${arm_radius} 0.23 ${arm_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.1" x="${arm_radius}" y="0.23" z="${arm_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="arm">
        <material>Gazebo/Orange</material>
    </gazebo>
    
    
    <!-- DOZER LINK -->

    <joint name="dozer_joint" type="fixed">
        <parent link="left_arm_link"/>
        <child link="dozer"/>
        <origin xyz="0.65 0 0.2"/>
    </joint>

    <link name="dozer">
        <visual>
            <origin xyz="0.1 0 -0.1"/>
            <geometry>
                <box size="0.02 0.6 0.4"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0.1 0 -0.1"/>
            <geometry>
                <box size="0.02 0.6 0.4"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.1" x="0.02" y="0.6" z="0.4">
            <origin xyz="0.1 0 -0.1" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="dozer">
        <material>Gazebo/Orange</material>
    </gazebo> 
    
    
    
    <joint name="dozer_left" type="fixed">
        <parent link="dozer"/>
        <child link="dozer_left"/>
        <origin xyz="0.29 -0.31 0"/>
    </joint>
    
    <link name="dozer_left">
        <visual>
            <origin xyz="0.1 0 -0.1"/>
            <geometry>
                <box size="0.6 0.02 0.4"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0.1 0 -0.1"/>
            <geometry>
                <box size="0.6 0.02 0.4"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.1" x="0.6" y="0.02" z="0.4">
            <origin xyz="0.1 0 -0.1" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="dozer_left">
        <material>Gazebo/Blue</material>
    </gazebo> 
    
    
    
    <joint name="dozer_right" type="fixed">
        <parent link="dozer"/>
        <child link="dozer_right"/>
        <origin xyz="0.29 0.31 0"/>
    </joint>
    
    
    <link name="dozer_right">
        <visual>
            <origin xyz="0.1 0 -0.1"/>
            <geometry>
                <box size="0.6 0.02 0.4"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0.1 0 -0.1"/>
            <geometry>
                <box size="0.6 0.02 0.4"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.1" x="0.6" y="0.02" z="0.4">
            <origin xyz="0.1 0 -0.1" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="dozer_right">
        <material>Gazebo/Blue</material>
    </gazebo> 
    
    
    <joint name="dozer_base" type="fixed">
        <parent link="dozer"/>
        <child link="dozer_base"/>
        <origin xyz="0.29 0 -0.21"/>
    </joint>
    
    
    <link name="dozer_base">
        <visual>
            <origin xyz="0.1 0 -0.1"/>
            <geometry>
                <box size="0.6 0.64 0.02"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0.1 0 -0.1"/>
            <geometry>
                <box size="0.6 0.64 0.4"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.1" x="0.6" y="0.64" z="0.4">
            <origin xyz="0.1 0 -0.1" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="dozer_base">
        <material>Gazebo/Blue</material>
    </gazebo> 
    
    
    
    <!-- RIGHT ARM JOINT -->
    <!-- arm_joint describes the rotation of the arm and is centred around the top corner of the slider box. -->
    <!-- - The axis of rotation is -1 in Y, so that positive is "up" -->
    <!-- - The upper limit uses xacro's mathematical features -->
    <joint name="right_arm_joint" type="fixed">
        <origin xyz="0.225 0 0" rpy="0 0 0"/>
        <parent link="arm_link"/>
        <child link="right_arm_link"/>
        <axis xyz="0 -1 0"/> 
    </joint>


    <!-- arm_link describes the arm -->
    <!-- - We use the "property" feature to define the arm length and radius and use them multiple times -->
    <!-- - The visual/collision origin is set to halfway along the length (similar to the box), but also with a rotation (again using the mathematical features). -->
    <!--   This is because the cylinder extends along the Z axis by default, but we want it to be along the X axis (when the joint is at 0) -->

    <xacro:property name="arm_length" value="0.75" />
    <xacro:property name="arm_radius" value="0.02" />
    <link name="right_arm_link">
        <visual>
            <origin xyz="0 0.125 0"/>
            <geometry>                
                <box size="${arm_length} ${arm_radius} ${arm_radius}" />
            </geometry>
            <material name="orange" />
        </visual>
        <collision>
            <origin xyz="0 0.125 0"/>
            <geometry>
                <box size="${arm_length} ${arm_radius} ${arm_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.075" x="${arm_length}" y="${arm_radius}" z = "${arm_radius}">
            <origin xyz="0 0.125 0"/>
        </xacro:inertial_box>
    </link>
    
    <gazebo reference="right_arm_link">
        <material>Gazebo/Blue</material>
    </gazebo>
 
    


</robot>
