<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>
    
    <xacro:property name="chassis_length" value="1.35" />
    <xacro:property name="chassis_width" value="0.5" />
    <xacro:property name="chassis_height" value="0.01" />
    <xacro:property name="chassis_mass" value="1.0" />
    <xacro:property name="wheel_radius" value="0.1778" />
    <xacro:property name="wheel_thickness" value="0.07" />
    <xacro:property name="wheel_mass" value="0.05" />
    <xacro:property name="wheel_offset_x" value="0.2135" />
    <xacro:property name="wheel_offset_y" value="0.285" />
    <xacro:property name="wheel_offset_z" value="0.01" />
    <xacro:property name="caster_wheel_radius" value="0.1778"/>
    <xacro:property name="caster_wheel_mass" value="0.01"/>
    <xacro:property name="caster_wheel_offset_x" value="1.1365" />
   

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <!-- BASE LINK -->

    <link name="base_link">

    </link>
    
    
    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
    	<parent link="base_link"/>
    	<child link="base_footprint"/>
    	<origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>
    
    <link name="base_footprint">
    </link>


    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="${-wheel_offset_x} 0 ${-wheel_offset_z}"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/White</material>
    </gazebo>
    

    <!-- BACK LEFT WHEEL LINK -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0  ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="0.07"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>




    <!-- BACK RIGHT WHEEL LINK -->

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>
    
    
    
    
    <!-- FRONT LEFT WHEEL LINK -->

    <joint name="front_left_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="front_left_wheel"/>
        <origin xyz="${caster_wheel_offset_x} ${wheel_offset_y} ${wheel_offset_z}" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="front_left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${caster_wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${caster_wheel_mass}" length="${wheel_thickness}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>


    <gazebo reference="front_left_wheel">
        <material>Gazebo/Blue</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>
    
    
    <!-- FRONT RIGHT WHEEL LINK -->

    <joint name="front_right_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="front_right_wheel"/>
        <origin xyz="${caster_wheel_offset_x} ${-wheel_offset_y} ${wheel_offset_z}" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="front_right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${caster_wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${caster_wheel_mass}" length="${wheel_thickness}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="front_right_wheel">
        <material>Gazebo/Blue</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>
    
    
    <!-- TOWER -->
    <!-- Needs to be 0.510m tall -->

    <joint name="tower" type="fixed">
        <parent link="base_link"/>
        <child link="tower"/>
        <origin xyz="0.4615 0 0"/>
    </joint>

    <link name="tower">
        <visual>
            <origin xyz="0 0 0.025"/>
            <geometry>
                <box size="0.05 0.5 0.05"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0 0 0.025"/>
            <geometry>
                <box size="0.05 0.5 0.05"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="0.05" y="0.5" z="0.05">
            <origin xyz="0 0 0.025" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="tower">
        <material>Gazebo/White</material>
    </gazebo>
    
    <!-- MOTOR AND GEARBOX LINK -->

    <joint name="motor_joint" type="fixed">
        <parent link="base_link"/>
        <child link="motor"/>
        <origin xyz="0 0 0"/>
    </joint>

    <link name="motor">
        <visual>
            <origin xyz="0 0 0.0375"/>
            <geometry>
                <box size="0.2 0.5 0.075"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0 0 0.0375"/>
            <geometry>
                <box size="0.2 0.5 0.075"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="1.5" x="0.2" y="0.5" z="0.075">
            <origin xyz="0 0 0.0375" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="motor">
        <material>Gazebo/Orange</material>
    </gazebo>
    
    
    
    <!-- TOWER HEIGHT LEFT -->
    <!-- Needs to be 0.510m tall -->

    <joint name="tower_up_left" type="fixed">
        <parent link="base_link"/>
        <child link="tower_up_left"/>
        <origin xyz="0.4615 0 0"/>
    </joint>

    <link name="tower_up_left">
        <visual>
            <origin xyz="0 -0.24 0.25"/>
            <geometry>
                <box size="0.05 0.02 0.410"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0 -0.24 0.25"/>
            <geometry>
                <box size="0.05 0.02 0.410"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="0.05" y="0.02" z="0.410">
            <origin xyz="0 -0.24 0.25" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>
    

    
    <!-- TOWER HEIGHT RIGHT-->
    <!-- Needs to be 0.510m tall -->

    <joint name="tower_up_right" type="fixed">
        <parent link="base_link"/>
        <child link="tower_up_right"/>
        <origin xyz="0.4615 0 0"/>
    </joint>

    <link name="tower_up_right">
        <visual>
            <origin xyz="0 0.24 0.25"/>
            <geometry>
                <box size="0.05 0.02 0.410"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0 0.24 0.25"/>
            <geometry>
                <box size="0.05 0.02 0.410"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="0.05" y="0.02" z="0.410">
            <origin xyz="0 0.24 0.25" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>
    
    
    
    <!-- TOWER TOP -->
    <!-- Needs to be 0.510m tall -->

    <joint name="tower_top" type="fixed">
        <parent link="base_link"/>
        <child link="tower_top"/>
        <origin xyz="0.4615 0 0"/>
    </joint>

    <link name="tower_top">
        <visual>
            <origin xyz="0 0 0.435"/>
            <geometry>
                <box size="0.05 0.5 0.05"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0 0 0.435"/>
            <geometry>
                <box size="0.05 0.5 0.05"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="0.05" y="0.5" z="0.05">
            <origin xyz="0 0 0.435" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>
       

     
</robot>
